
---
# This playbook deploys kubernetes in our specific predefined vagrant context

- name: apply common configuration to all nodes
  hosts: k8s_inside
  roles:
    - common

- name: Deploy K8s Master
  hosts: kumaster

  roles:
    - k8s_master

  handlers:
    - include: roles/k8s_master/handlers/handlers.yaml

- name: Deploy K8s Node
  hosts: kunode

  roles:
    - k8s_node

  handlers:
    - include: roles/k8s_node/handlers/handlers.yaml

