---
image: docker:latest
services:
  - docker:dind

variables:
  REGISTRY_PATH: docker.io/patchshorts
  DOCKER_DRIVER: overlay2

stages:
  - build
  - test
  - push
  - stage

before_script:
  - echo "${DOCKERPASS_BASE64}" | base64 -d | docker login -u patchshorts --password-stdin

.dockerbuild:
  stage: build
  tags: [ docker ]

.dockertest:
  stage: test
  tags: [ docker ]

.dockerpush:
  stage: push
  tags: [ docker ]

# Puppetserver
.puppetserver:
  extends: .dockerbuild
  script:
    - docker build -t ${REGISTRY_PATH}/puppetserver puppetserver
    - docker tag ${REGISTRY_PATH}/puppetserver ${REGISTRY_PATH}/puppetserver:${TAG}
    - docker run ${REGISTRY_PATH}/puppetserver "--version"
    - docker push ${REGISTRY_PATH}/puppetserver:${TAG}

puppetserver_devel:
  variables:
    TAG: "${CI_COMMIT_REF_NAME}-${CI_COMMIT_SHORT_SHA}"
  extends: .puppetserver
  only: [ devel ]

puppetserver:
  variables:
    TAG: "${CI_COMMIT_TAG}"
  extends: .puppetserver
  only: [ tags ]

# PuppetDB
.puppetdb:
  extends: .dockerbuild
  script:
    - docker build -t ${REGISTRY_PATH}/puppetdb puppetdb
    - docker tag ${REGISTRY_PATH}/puppetdb ${REGISTRY_PATH}/puppetdb:${TAG}
    - docker run ${REGISTRY_PATH}/puppetdb "--version"
    - docker push ${REGISTRY_PATH}/puppetdb:${TAG}

puppetdb_devel:
  variables:
    TAG: "${CI_COMMIT_REF_NAME}-${CI_COMMIT_SHORT_SHA}"
  extends: .puppetdb
  only: [ devel ]

puppetdb:
  variables:
    TAG: "${CI_COMMIT_TAG}"
  extends: .puppetdb
  only: [ tags ]

# webhook
.webhook:
  extends: .dockerbuild
  script:
    - docker build -t ${REGISTRY_PATH}/webhook webhook
    - docker tag ${REGISTRY_PATH}/webhook ${REGISTRY_PATH}/webhook:${TAG}
    - docker run ${REGISTRY_PATH}/webhook "--version"
    - docker push ${REGISTRY_PATH}/webhook:${TAG}

webhook_devel:
  variables:
    TAG: "${CI_COMMIT_REF_NAME}-${CI_COMMIT_SHORT_SHA}"
  extends: .webhook
  only: [ devel ]

webhook:
  variables:
    TAG: "${CI_COMMIT_TAG}"
  extends: .webhook
  only: [ tags ]
