version: '3.7'

services:
  puppet:
    hostname: puppet
    domainname: local
    # build: puppetserver
    image: patchshorts/puppetserver:${PUPPETSERVER_VERSION:-5.3-devel}
    ports:
      - "0.0.0.0:8140:8140"
    environment:
      # necessary to set certname and server in puppet.conf, required by
      # puppetserver ca cli application
      - PUPPETSERVER_HOSTNAME=${PUPPETSERVER_HOSTNAME:-puppet}
      # DNS_ALT_NAMES must be set before starting the stack the first time,
      # and must list all the names under which the puppetserver can be
      # reached. Add other names as a comma-separated list
      - CA_ALLOW_SUBJECT_ALT_NAMES=${CA_ALLOW_SUBECT_ALT_NAMES:-true}
      - DNS_ALT_NAMES=${DNS_ALT_NAMES:-puppet.local}
      - ANALYTICS_ENABLED=${ANALYTICS_ENABLED:-false}
      - PUPPETDB_HOSTNAME=${PUPPETDB_HOSTNAME:-puppetdb.local}
      - PUPPETDB_SERVER_URLS=https://${PUPPETDB_HOSTNAME:-puppetdb.local}:8081
      - HIERA_BASE64=${HIERA_BASE64:-}
      - EYAML_PUBLIC_BASE64=${EYAML_PUBLIC_BASE64:-LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUMyVENDQWNHZ0F3SUJBZ0lCQVRBTkJna3Foa2lHOXcwQkFRVUZBREFBTUNBWERUSXdNRFV4TmpBM01UWXkKTUZvWUR6SXdOekF3TlRBME1EY3hOakl3V2pBQU1JSUJJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBUThBTUlJQgpDZ0tDQVFFQTFIUUVTN2xZTEFPNkdlV3ZFNk83UEw3RTJjckJaemtmZnpod1o2SlBpMnVlWGZQdlFnaUkvL1VjCkRXK3hvOWxZem41UG5JeTZ2eCtmNUZKMTc1bnFPNHVLaE1sMXFRVmRBNzNRS21qWDM4eFFPeGlkZ1hBc0xqVTEKUTJHV1JaMVR0bjRIM2Zacll4QzlGRmJ5ZXdPL095TnZTbDNHODgydnpZbDdWVUdpSUs1bVFRNDlpdWQxYm1TTwp4NWt0dmFyQk5wdjhBRDZISnlWc2FqVTFBd2d4TDltb0Y4NHZTQ3dJMFYwRlFpeng1RnBtbmZ3R040dU56Q09RClIxSGZZVXEvUG50RzROeGxOcVBVdVc5dmp3bmZvRXZTVW95aVUwQ0Y5Y05hVW1scWhJeEFiakN0Z0RaeGV4N0EKRjkwTll3WEVKVm9sUmZnZGszeG8vN1l5eVBMbTdRSURBUUFCbzF3d1dqQVBCZ05WSFJNQkFmOEVCVEFEQVFILwpNQjBHQTFVZERnUVdCQlE3TW8rRXdpcWVWc29yaktwelBNT2p5MnlTY0RBb0JnTlZIU01FSVRBZmdCUTdNbytFCndpcWVWc29yaktwelBNT2p5MnlTY0tFRXBBSXdBSUlCQVRBTkJna3Foa2lHOXcwQkFRVUZBQU9DQVFFQWRrNTAKZTVaclVNZjhSdU5sbW11UzF0NHZFMVhwT1VKNUVVMTlsbFphcDZFNXIyU3prM0lsRDdsTmx0ampjSXY4cE1Vdwp6MEFHazVlSjNGM2lkbTludGZZR1RoVnBSdUNEbGU0SEdra2ZFdUlIMk15S1IxZG0xWWtUV2VPTWlRTnlTVWVUCnJpdVVjV0MrV2c1L1gxa09lM0hKaHFkL25iWDFnN2ZYSFQvYlNjY2VKV3FpdUdKaDNvOWIzZzdUeSs1cDNLdzYKZUx1RStGVXRoTjE4UW9JeG5RYnU5bjB1aTU3YXBVNUpDQUFtUXZrZytBdnY2UjU5OVk4ckdjQTJlaGRRSnIyZwpHZTZjQ2lVbU9OU3lXbU4xM3ZvT1F6ci9kanl4bkZ4NHNwM0k5K0RrUTYyb3ZDWXZnZmwzZUtuSUZzQlJON3dnCk1yT0N3SktEQjc0NmJaV0thQT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K}
      - EYAML_PRIVATE_BASE64=${EYAML_PRIVATE_BASE64:-LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFcEFJQkFBS0NBUUVBMUhRRVM3bFlMQU82R2VXdkU2TzdQTDdFMmNyQlp6a2Zmemh3WjZKUGkydWVYZlB2ClFnaUkvL1VjRFcreG85bFl6bjVQbkl5NnZ4K2Y1RkoxNzVucU80dUtoTWwxcVFWZEE3M1FLbWpYMzh4UU94aWQKZ1hBc0xqVTFRMkdXUloxVHRuNEgzZlpyWXhDOUZGYnlld08vT3lOdlNsM0c4ODJ2ellsN1ZVR2lJSzVtUVE0OQppdWQxYm1TT3g1a3R2YXJCTnB2OEFENkhKeVZzYWpVMUF3Z3hMOW1vRjg0dlNDd0kwVjBGUWl6eDVGcG1uZndHCk40dU56Q09RUjFIZllVcS9QbnRHNE54bE5xUFV1Vzl2anduZm9FdlNVb3lpVTBDRjljTmFVbWxxaEl4QWJqQ3QKZ0RaeGV4N0FGOTBOWXdYRUpWb2xSZmdkazN4by83WXl5UExtN1FJREFRQUJBb0lCQUZSbEtmZXl6dlhkSFNhQQplVVlCK3JVc3l5SUJTMGJvQ0QwUGZJZU9rSzYvdDQ5M0FZcG52WlNBRi82MmFnaStwR3FTL3FrZnRtZUo5b2hLCndaTEd2NmVielJEbXZwakFDcTBiei8rbzJtaUt6eXhLb1BiMFNuaW9wbG40QUN2elRYZm5KTlRsdU04SHJUVFIKUFUza3RTaVc4UFRIdityRndKcVRqS3pYZjhJZkM4SVg1dkY2UXNTVlc5d05oRjBjSDk0eEdOL0NMeXErMTlLWQpETHV1N0hHRGlUYnNqOHNKdUl3UzkrUjJQaUNPZGsvOGtDekRhUUx3TEJ5S0xzSVFxZGxyV1Q4eWRHd3lrSlBvCng5U01hVFY0d2FnNVo3dDJQbk5yQ0VjK1p6ZHREVDRubGpwTzc1NFdZMzdWb2dsRHBpT3A1WVZoazNGa05BbU8KNmorSWJ6a0NnWUVBK2RTWDlMbVJra3ozQVMxSFppQTlBd3lNVmg1T1YxbVgwUVRhN0srU0tyc3NDZHB3bkdYdgorYzQ5N3ZmRWJId29IYWliT0ZGM2dHcFJRRnlSeU5hd1FlOHVTTXIvWU4vS1o2aThUdXY2S252RHZCYVRNZm9HCkZBYTB4QVNUaHByQ3I2Z1pIL2NpaTVzd0tIVGxlamoxQmpMVnNEV1o2eHpodjJ1a0FFZlFCd3NDZ1lFQTJiTWcKb0ZJS251c2xtNysyTm9JNW1OcUtKQVFDa040NjltRU1CQi82THZieksvUGZxVVNyc0xhQlVtL0xDNEZ4U2NlMApKbE9MOFNnNTRzS3F2SzZ0ZlA2SnQyWDM0cC9TZy9QVjRZT0lqNmpLTE5kWmdyVm41VGtDS1N2aVg4Rmp1YkFuCjFVS3pBRnNHYnEzQXdXbEw3TE9haC8yRVBtNUUzTm4vQVMwZEpPY0NnWUVBMFJvOE9VdmNhS3hjalRLZHNQL0kKc1RXZWZESVBkaEw1KzZ0cHBYTHFEelBzRHk4eTArU0tML2FNWmVnaEVuLzBmNlp3akhtN1lOTWJ3SmY2T1RSZwpBRCsxNkoxbmxHaWJHNW5pU3RnOTRiTUhSL1ZKTENwTlRoT3kxdUhSckhiNS9sWGUrWjg2M2NoOVRVOVNCck9ICmViR3dvelNwNkZ5YklrRncyZjlCUWJNQ2dZRUFwdzF2c2RhQzArUDVuZ1NFM0ZzZHU0K25oVytXVUhoWG9veGgKM2lCenFPcFRPNTBPT2lPNTVBYUlRaXdMRVM4cE1jYVBGUUh6VndEWk9vckszYkxrNmcrZ3VoMERGT0l6ZHBINwp3K3RkTlcvK2hGNVVENXNJdUxzQVQzdWZZSDlUK1QrVnNXNVhVYVNIMFJKLzRXcmRtaXRRSDU2SWhpZXpyQTJVClF1RE5obTBDZ1lCT3JtT3RYSFpPWGd5RzJGZ2E5UXIySnhnL3VaOEdaNFVnWHBFMkFmNy9KemQwSDUrY1F4cTMKTXBRVDRMa09EOXVMQkVRT3Y1dkxiMFVPV3JWNmVaSzRaS0lxZTlyTFBMQlU1K3N5V2NUZWxxUEZGRWJaNlZFcApjd0N3WVZqNW1QTm5wMkpaNUpSSG84NGZxVHg2MHFZYTJqSmFETFFNbmI4NEQxZFY1bGFoQ1E9PQotLS0tLUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQo=}
      - SERVER_FACTS_BASE64=${SERVER_FACTS_BASE64:-IyEvYmluL3NoCmVjaG8gImN1c3RvbWVyPWludGVybmFsIgplY2hvICJhcHA9aW5mcmFzdHJ1Y3R1cmUiCmVjaG8gInN0YWdlPWluZnJhc3RydWN0dXJlIgplY2hvICJoaWVyYV92ZXJzaW9uPSJgL3Vzci9iaW4vZW52IGhpZXJhIC1WIDI+JjEgfCBncmVwIC12IElnbm9yaW5nIHwgYXdrIC1GLiAne3ByaW50ICQxfSdgCg==}
      - ENVIRONMENT=${ENVIRONMENT:-infrastructure}
    volumes:
      - puppetserver-code:/etc/puppetlabs/code/
      - puppetserver-config:/etc/puppetlabs/puppet/
      - puppetserver-data:/opt/puppetlabs/server/data/puppetserver/
    depends_on:
      - webhook
    links:
      - puppetdb:puppetdb.local
  postgres:
    image: postgres:9.6
    hostname: postgres
    domainname: local
    environment:
      - POSTGRES_PASSWORD=puppetdb
      - POSTGRES_USER=puppetdb
      - POSTGRES_DB=puppetdb
    healthcheck:
      # existence check for puppetdb database
      test: [ 'CMD-SHELL', "psql --username=puppetdb puppetdb -c ''" ]
      interval: 10s
      timeout: 5s
      retries: 6
      start_period: 2m
    expose:
      - 5432
    volumes:
      - puppetdb-postgres:/var/lib/postgresql/data
      - ./postgres-custom:/docker-entrypoint-initdb.d
  puppetdb:
    hostname: puppetdb
    domainname: local
    image: patchshorts/puppetdb:${PUPPETDB_VERSION:-5.2-devel}
    environment:
      - ANALYTICS_ENABLED=${ANALYTICS_ENABLED:-false}
      # This name is an FQDN so the short name puppet doesn't collide outside compose network
      - PUPPETSERVER_HOSTNAME=${PUPPETSERVER_HOSTNAME:-puppet}
      - PUPPETDB_POSTGRES_HOSTNAME=${PUPPETDB_POSTGRES_HOSTNAME:-postgres}
      - PUPPETDB_PASSWORD=${PUPPETDB_PASSWORD:-puppetdb}
      - PUPPETDB_USER=${PUPPETDB_USER:-puppetdb}
      - DNS_ALT_NAMES=${DNS_ALT_NAMES:-puppetdb.local}
      - CERTNAME=${PUPPETDB_CERTNAME:-puppetdb}
    ports:
      - "0.0.0.0:8080:8080"
      - "0.0.0.0:8081:8081"
    depends_on:
      - postgres
    volumes:
      - puppetdb:/opt/puppetlabs/server/data/puppetdb/
  webhook:
    hostname: webhook
    domainname: local
    # build: webhook
    image: patchshorts/webhook:${WEBHOOK_VERSION:-5.5-devel}
    environment:
      - R10K_CONTROL_REPO=${R10K_CONTROL_REPO:-ssh://git@gitlab.com/puppet-control/sample-control.git}
      - R10K_HIERA_REPO=${R10K_HIERA_REPO:-}
      - R10K_DEPLOY_KEY_BASE64=${R10K_DEPLOY_KEY_BASE64:-LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFcFFJQkFBS0NBUUVBNmw3Vi9GS05mU0pUUHNWY3RpRXJ1RmFvTnNqN1ZNS1hxTmlreDhPaVRIZ1ErVmlBCkhSdVlJUGZnNHE1SHIvNVRrYjZmYW54Y2p0RFVjWGdWT0Q0WE83NE9ZWWhBYlVIWXU5N1hqdkJkcEJXS2R4cmoKcWJDdUlpbzhFN3N0aFgyWno1ZXFybDZoV0tOcjNqQVVTRlFKdlF6amcxR3JEWENHenVucjFWYjhqbUg0RkZYTgo2UURUQXBOdWNSclhUaEw1YWlSQVRMQ295My9ES3k5OUllVE9vdk9JL0ltY29GK0ZacjNqa2VFR3ZzN3gvNTFiCmJuaXl3WTltUnpLNHoveTlaanRnWEpZOFNKZzJsN3lHa0l6eGYxeG1pc21LN2dId2NyL2lMTDZjMFJNczNhS0YKMERuQ1prUXpmVFdwdytzUHVOZ1R2bldLQnFlak5FRzN0emJNWFFJREFRQUJBb0lCQUErYVRxNmtwRXkvVzBGagpqRCtIeDh4VzRJMzlKVlpJT2lhQWZiL2EwMVE1N2c5YmgvUG9JV0dZZnYwNFV3ZHhiQWpZNHU0STUzU09qSVlkClUzUlNGZVBoVEQzTC8xWUd1eklPck5VVVJYZW1BM2pZYm0yZW1Ja252S1lub09reEttczZrcDlYSjNDcU9JVXIKT0Q1MGNjMkhMU0pSN294UGdIb0g4cTVhUXlnTFZ3VWUwTVZoQUlCckFJN2xkMWx2WW4wWkFHQStOdG80NmFEcQpmQlllOWZQUDBTaEhkdE1nMEtZN2gxeTQ0UGpwRzNxUk5FYkFmd2ZBV2RzRE5LOUJFQm9uY2ZFLzhJY2Ivd3ZkClkyZU9PU3lUOGI1UVAvMVcrTmR2ZjNyQmc4ZFd4Q01HNW5ZMWJMbGU0UGtyK3B4Ulg4YjNHSVhlRmlkQXB5SVUKRXFhN1lhRUNnWUVBK1ZWUDNPWTRuM0NTcUhnL0tVb2x1bjBSS0w0RkNWbFhleHBjd2dqckdjSzdZbVBTcEthTQptUmhnUEx5SFJJTGQrNmlXMUlsNHdCSlBrcVc2OVlNOHFjd1BCeGlwbm1qOGhiaSsvRGxnaVRyb0VlMVVCM0xrCnVvaGI2aFVGZUZJK0U5b1plZlJjQVZIb3dUVm9JZnRhaEo2TGloZ2R2aEI5S3A4WjRHRWtTYmtDZ1lFQThLTWEKZS9GQVlCU0duT2ZJUG11OUl2Zm1scUlzcytYZzhQRnMzdHFaMDdHV0NHNk1xR0NrNEVaZ0k4d0IwbzduUWd6Ugo1NGtDcU9wUUdsQWo3d3Rtb25hemg5OFJpVldTdzF5bHNCSnRqWHFwMHM5ellpMXVLL20rVlgwZFJSR2JHVUs1CjgrbTRZYzJQUElmd0MxRGVPVW9nY2FkZEJJRXR5dnA1eElOUEdjVUNnWUVBdUdNZzVvblRBZ1lzVHk1dDkwa0EKVWNPLzl0TmZ3aVF5RDdYVk55R0ZTODI0NmZCTWpMc21hdW1kOGd5eU5EWmJsNHA3MEwzQmNMbVo0eWR3OWJPUwpIemZyUFNJOS9ncENCVm8wMHk1VGQrajZTcGVxZHIrKzZ6dUFUY0l5QTJNK3lVdVhYNXNZbDFsTnVlU1hGOXBjCmZJc0xRcHJIRkJINW5wVitlM01iZFBFQ2dZRUF0UzRaQXJqaWYzVDA1YTZlVm1GSVJzdmdFZ3FKSGVvM016S1QKaGplUkdwTGJJLzRZYWE1YWRZS0hZR3g1OHM4bHo5VlhOYjB6QTN0b1ZHZUNwcmt1emFRU0NIc3IrUHMxUldLOApYWldDWnNPMG1jVVlXeE5ab0VLcHpEUW5sWmxyN2RrUHFWYVFQUk5JaFlyVWNiQ3hvUER1L0tQR3BWMmQzUFk2Ck9IdWxVd0VDZ1lFQTFDOTQzZDh2d0MwTytzWEsyMVVQeTZuWXNXdVNuYlNyKzNQSE84WkVRVjh2QnRleFplMDYKS3dxZFg3WWt4RlJFVlVmUURiTlczRWJ0UGlNRVRzMWw4djBUTkFxbm9McmQ1aUJpRk1CQkNNWDZYT0x0aXZNawpRbmV2Z29ER0FoYjVwNFczRWR6ckkwcVRwaGx0YlNWK0tVYjhpM0NXUldmNG8yRitUV1pXSkJRPQotLS0tLUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQo=}
    ports:
      - "0.0.0.0:8088:8088"
    volumes:
      - puppetserver-code:/etc/puppetlabs/code/

volumes:
  puppetserver-code:
  puppetserver-config:
  puppetserver-data:
  puppetdb:
  puppetdb-postgres:
