apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  creationTimestamp: null
  labels:
    io.pik.service: postgres
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      io.pik.service: postgres
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
      creationTimestamp: null
      labels:
        io.pik.service: postgres
    spec:
      containers:
      - env:
        - name: POSTGRES_DB
          value: puppetdb
        - name: POSTGRES_PASSWORD
          value: puppetdb
        - name: POSTGRES_USER
          value: puppetdb
        image: postgres:12
        securityContext:
          runAsUser: 0
        ports:
          - containerPort: 5432
        name: postgres
        resources: {}
        volumeMounts:
        - mountPath: /var/lib/postgresql/
          name: puppetdb-postgres
      hostname: postgres
      restartPolicy: Always
      subdomain: default
      volumes:
      - name: puppetdb-postgres
        persistentVolumeClaim:
          claimName: puppetdb-postgres
status: {}
