apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.pik.service: puppetserver-config
  name: puppetserver-config
spec:
  resources:
    requests:
      storage: 100Mi
  accessModes:
    - ReadWriteMany
status: {}
