apiVersion: v1
kind: Service
metadata:
  annotations:
  creationTimestamp: null
  labels:
    io.pik.service: puppet
  name: puppet
spec:
  ports:
  - name: "8140"
    port: 8140
    targetPort: 8140
  selector:
    io.pik.service: puppet
status:
  loadBalancer: {}
