apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.pik.service: puppetserver-data
  name: puppetserver-data
spec:
  storageClassName: managed-nfs-storage
  resources:
    requests:
      storage: 100Mi
  accessModes:
    - ReadWriteMany
status: {}
