apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  creationTimestamp: null
  labels:
    io.pik.service: puppet
  name: puppet
spec:
  replicas: 1
  selector:
    matchLabels:
      io.pik.service: puppet
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
      creationTimestamp: null
      labels:
        io.pik.service: puppet
    spec:
      containers:
      - env:
        - name: ENVIRONMENT
          value: infrastructure
        - name: SERVER_FACTS_BASE64
          value: "IyEvYmluL3NoCmVjaG8gImN1c3RvbWVyPWludGVybmFsIgplY2hvICJhcHA9aW5mcmFzdHJ1Y3R1cmUiCmVjaG8gInN0YWdlPWluZnJhc3RydWN0dXJlIgplY2hvICJoaWVyYV92ZXJzaW9uPSJgL3Vzci9iaW4vZW52IGhpZXJhIC1WIDI+JjEgfCBncmVwIC12IElnbm9yaW5nIHwgYXdrIC1GLiAne3ByaW50ICQxfSdgCg=="
        - name: DNS_ALT_NAMES
          value: puppet
        - name: PUPPETDB_SERVER_URLS
          value: "https://puppetdb:8081"
        - name: PUPPETDB_HOSTNAME
          value: "puppetdb"
        image: patchshorts/puppetserver:1.0.5
        name: puppet
        securityContext:
          runAsUser: 0
        ports:
        - containerPort: 8140
        resources: {}
        volumeMounts:
        - mountPath: /etc/puppetlabs/code/
          name: puppetserver-code
        - mountPath: /etc/puppetlabs/puppet/
          name: puppetserver-config
        - mountPath: /opt/puppetlabs/server/data/puppetserver/
          name: puppetserver-data
      hostname: puppet
      restartPolicy: Always
      volumes:
      - name: puppetserver-code
        persistentVolumeClaim:
          claimName: puppetserver-code
      - name: puppetserver-config
        persistentVolumeClaim:
          claimName: puppetserver-config
      - name: puppetserver-data
        persistentVolumeClaim:
          claimName: puppetserver-data
status: {}
