apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.pik.service: puppetdb
  name: puppetdb
spec:
  securityContext:
    runAsUser: 3000
    fsGroup: 3000
  storageClassName: local
  resources:
    requests:
      storage: 100Mi
  accessModes:
    - ReadWriteOnce
status: {}
