apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv003
spec:
  capacity:
    storage: 100Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: local
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /.data/puppetserver-code
    server: 10.0.3.30
