apiVersion: v1
kind: Service
metadata:
  annotations:
  creationTimestamp: null
  labels:
    io.pik.service: webhook
  name: webhook
spec:
  ports:
  - name: "8088"
    port: 8088
    targetPort: 8088
  selector:
    io.pik.service: webhook
status:
  loadBalancer: {}
