- name: Install Docker
  apt:
    name: "docker.io"
    state: "present"
- name: Start & enable docker
  systemd:
    state: started
    daemon_reload: yes
    name: docker
    enabled: true
  register: docker_enabled
