- name: Add google cloud apt key
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present

- name: Add YQ PPA apt repo
  apt_repository:
    repo: deb http://apt.kubernetes.io/ kubernetes-xenial main

- name: Install k8s
  apt: name={{ item }} state=present
  with_items:
   - kubeadm
   - kubectl
   - kubelet
  register: install_k8s

- name: Disable swap (if configured).
  command: swapoff -a
  tags: ['skip_ansible_lint']

- name: Remove current swaps from fstab
  lineinfile:
    dest: /etc/fstab
    regexp: '(?i)^([^#][\S]+\s+(none|swap)\s+swap.*)'
    line: '# \1'
    backrefs: yes
    state: present

- name: Disable swappiness and pass bridged IPv4 traffic to iptable's chains
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: present
  with_items:
    - { name: 'vm.swappiness', value: '0' }
    - { name: 'net.bridge.bridge-nf-call-iptables', value: '1' }
