# Create volumes in k8s
# TODO: make thse inline definitions pulled from vars(if possible)
- name: Create NFS Volume Infrastructure
  when: init_k8s_cluster is succeeded
  k8s:
    src: /vagrant/provision/k8s-yaml/nfs/{{ item }}
    state: present
    namespace: default
  with_items:
    - rbac.yaml
    - default-sc.yaml
    - deployment.yaml

- name: Create volumesclaims
  when: init_k8s_cluster is succeeded
  k8s:
    src: /vagrant/provision/k8s-yaml/{{ item }}
    state: present
    namespace: default
  with_items:
    - puppetdb-persistentvolumeclaim.yaml
    - puppetdb-postgres-persistentvolumeclaim.yaml
    - puppetserver-code-persistentvolumeclaim.yaml
    - puppetserver-config-persistentvolumeclaim.yaml
    - puppetserver-data-persistentvolumeclaim.yaml
