---
- name: Deploy CNI
  when: init_k8s_cluster is succeeded and network == 'calico'
  command: |
      kubectl --kubeconfig={{ kubeadm_config }} \
        apply -f kubectl apply -f https://docs.projectcalico.org/manifests/calico.yaml
  register: k8s_net
  retries: 5
  delay: 2
  ignore_errors: true
