- name: kubeadm tasks
  import_tasks: k8s-kubeadm.yml

- name: configureing kubectl on the master
  import_tasks: k8s-master-config.yml

- name: apply net
  import_tasks: k8s-net.yml

- name: configuring kubectl on vagrant host
  import_tasks: k8s-kubectl-vagrant.yml

- name: configuring kubectl on vagrant host
  import_tasks: storage-config.yml

- name: installing volumes into k8s
  import_tasks: k8s-volumes.yml

- name: installing deployments into k8s
  import_tasks: k8s-deployments.yml

- name: installing services into k8s
  import_tasks: k8s-services.yml
