---
- name: Create PV Mounts
  apt:
    name: nfs-kernel-server
    state: present
  register: install_nfs

- name: "Checking PV Mount points"
  file:
    path: "/srv/nfs/kubedata"
    state: directory
    mode: 0777
    group: 65534
    owner: 65534
  register: nfs_mkdir

- name: "nfs-kernel-server: Configure exports"
  template:
    src: "exports.j2"
    dest: "/etc/exports"
    owner: "root"
    group: "root"
    mode: "0644"
  notify: reload nfs-kernel-server
