---
- name: configureing kubectl on the master
  import_tasks: k8s-master-config.yml

  mkdir -p {$HOME}/.kube

  cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
  cp -i /etc/kubernetes/admin.conf /vagrant/.kube/kconfig
  chown $(id -u):$(id -g) $HOME/.kube/config
