---
- name: Reset the cluster incase vagrant provision was interupted.
  shell: "kubeadm --reset --force"
  tags: ['skip_ansible_lint']
  register: k8s-reset

- name: Initializing Kubernetes Cluster
  when: k8s-reset is succeeded
  shell: |
    kubeadm init --apiserver-advertise-address={{ k8s-master-ip }} \
                 --pod-network-cidr={{ pod_network_cidr }} \
                 --service-cidr {{ service_cidr }} \
                 --token {{ k8s-token }} \
                 {{ kubeadm_opts }} \
                 {{ init_opts }} > {{ vagrant_kinitout }}
    register: init_k8s_cluster

- name: Create Kubernetes config directory
  file:
    path: ".kube/"
    state: directory

- name: Copy admin.conf to Home directory
  when: init_cluster is succeeded
  copy:
    src: "{{ kubeadmin_config }}"
    dest: ".kube/config"
    mode: 0755
    remote_src: true

- name: Deploy kubernetes dashboard into cluster
  when: init_cluster is succeeded and enable_dashboard
  command: |
    kubectl --kubeconfig={{ kubeadmin_config }} \
        apply -f https://raw.githubusercontent.com/kubernetes/dashboard/master/aio/deploy/recommended.yaml
  register: create_result
  until: create_result.rc == 0
  retries: 5
  delay: 2
  ignore_errors: true
