---
- name: Create Kubernetes config directory
  file:
    path: "{{ vagrant_kubeconfig }}"
    state: directory
- name: Copy to {{ vagrant_kubeadm_config }} from admin.conf
  when: init_k8s_cluster is succeeded
  copy:
    src: "{{ kubeadmin_conf }}"
    dest: vagrant_kubeadm_config
    remote_src: yes
  register: k8s_conf_vag_copy
